# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 043fb359355704e8dbbdee360b03373858ea99a877d8b83456b3f986d60b793219b02784e326facfdc8490fe58a4173eb65107d6104c1f8f3674600dd4e5fe10

test:
  secret_key_base: bc3abfd095532660e20f9521c5b88a4c0a2c55f5bfc0f004397ec8f33ecf79e89fb411644ed00aa5cd872a3b677ff887fcac73fece4c017fb4e5b4d883593466

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
